### ISSUE TITLE
segfault at 14b659d3f3a0

### ISSUE THREAD

**Issue by anoma** [linuxserver/docker-tvheadend#101]
On recent builds  (190s) I am getting:

`tvh:mtimer[21724]: segfault at 14b659d3f3a0 ip 00005559a65a76d7 sp 000014b65dd9f4a0 error 6 in tvheadend[5559a6445000+3d5000]`

when switching between Kodi instances or profiles. I have rolled back to 185 and all my issues go away.

This is a placeholder ticket to see if anyone googles same issues and lands here. I will keep testing and close later if it is niche.

**Comment by michaelarnauts** [comment]
I also notice the latest tvheadend version to be quite unstable, but I guess this is not really related to this repo, unless it has something to do with the musl patches.

**Comment by tobbenb** [comment]
Better to report it to tvheadend, but might run a debug version of tvheadend.

**Comment by Fusl** [comment]
Rolling back to 192 solved this for me, it uses `4.3-1553~gbdc2ae9e1` as latest version, `4.3-1613~gf098a50cc` seems to be unstable with the lsio image. Tvheadend either crashes or hangs as soon as I stop a running stream. I'm using an `MPEG-TS Spawn/built-in` profile.

**Comment by tobbenb** [comment]
Latest tag is the development branch of tvheadend, and I suggest running release-4.2 for a stable server. Unless there is something in 4.3 that is needed for you to use tvheadend.
Going to close this one as it's most likely an issue with tvheadend.

**Comment by Fusl** [comment]
@tobbenb Do note that back then when I debugged this issue, I tested the exact same configuration on a plain Debian Stretch TVheadend installation, not running with in Docker, and found that the same behavior didn't trigger this segfault which is the reason I commented here instead of opening an issue over at the TVheadend issue tracker.

This is however no longer an issue for me since the last Docker image version works very well on my system now.

**Comment by tobbenb** [comment]
@Fusl I guess it got to do with alpine using musl. Probably somehow fixed upstream at some point.
