### ISSUE TITLE
Picons not working in kodi because of digest authentication

### ISSUE THREAD

**Issue by ReekyMarko** [linuxserver/docker-tvheadend#155]
Just spent a lot of times working out why picons were not working in kodi. Turns out kodi will fetch icons with basic authentication and this is why it was failing. Should we make the default as basic+digest so other people don't have to figure out why their picons are not working in kodi? I have no idea about the security aspect of all of this so I don't know if it's a good idea.

Actually kodi seems to be using curl to fetch the icons so they would just need to add `--anyauth` or `--digest` parameter to wherever curl is used so I might open an issue in their repo too.

**Comment by tobbenb** [comment]
Default settings is something that should be changed at the source, so better to ask the tvheadend developers. I really don't want to add default settings to the container as it's just bound to break at some point.

It's been some time since I have used tvheadend now, but I never had any issues getting the picons to load.

**Comment by ReekyMarko** [comment]
Aah okay maybe they changed the defaults since I did my bare metal install. I just thought the defaults were somehow set in this container. Sorry for the noise
